name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      
      - name: Build
        run: dotnet build -c Release /p:Version=${VERSION}
      
      - name: Test
        run: dotnet test -c Release /p:Version=${VERSION} --no-build
      
      - name: Pack
        run: dotnet pack -c Release /p:Version=${VERSION} --no-build --output .
      
      - name: Push
        run: dotnet nuget push OpenAssetImporter.${VERSION}.nupkg --source https://nuget.pkg.github.com/popcron/index.json --api-key ${ASSIMP_SECRET_TOKEN}
        env:
          ASSIMP_SECRET_TOKEN: ${{ secrets.ASSIMP_SECRET_TOKEN }}