name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test project
        run: dotnet test -c Debug --collect:"XPlat Code Coverage" --results-directory:"TestResults"